name: gnews_client
description: A Dart client for interacting with the GNews API.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  country_code: ^1.0.0
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^3.1.0
