name: news_server
description: A Dart frog app for serving news articles.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  country_code: ^1.0.0
  dart_frog: ^0.2.0
  dcache: ^0.4.0
  dotenv: ^4.0.1
  freezed_annotation: ^2.2.0
  gnews_client:
    path: ./packages/gnews_client
  json_annotation: ^4.7.0
  logging: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
